from collections.abc import Callable, Hashable, Iterator
from typing import Any, NamedTuple, TypeVar

_F = TypeVar("_F", bound=Callable[..., Any])
_T = TypeVar("_T")

class CacheInfo(NamedTuple):
    hits: int
    misses: int
    maxsize: int
    currsize: int

class Cache:
    def __init__(self, maxsize: int) -> None: ...
    def __repr__(self) -> str: ...
    def __len__(self) -> int: ...
    def __contains__(self, key: object) -> bool: ...
    def __iter__(self) -> Iterator[Hashable]: ...
    def __getitem__(self, key: Hashable) -> Any: ...
    def __setitem__(self, key: Hashable, value: Any) -> None: ...
    def __delitem__(self, key: Hashable) -> None: ...
    def get(self, key: Hashable, default: Any = None) -> Any: ...
    def pop(self, key: Hashable, default: _T = ...) -> Any | _T: ...
    def setdefault(self, key: Hashable, default: Any = None) -> Any: ...
    def clear(self) -> None: ...
    @property
    def maxsize(self) -> int: ...
    @property
    def hits(self) -> int: ...
    @property
    def misses(self) -> int: ...

def memoize(maxsize: int = 128, typed: bool = False) -> Callable[[_F], _F]: ...
